import type {
  Announcement,
  Course,
  EnrolledCourse,
  ExamCategory,
  Instructor,
  LearningStats,
  LiveClass,
  Order,
} from "@/types";

/* ─────────────────────────  Instructors  ───────────────────────── */

export const instructors: Record<string, Instructor> = {
  rohit: {
    id: "ins_rohit",
    name: "Prof. Rohit Sharma",
    title: "Data Structures & Algorithms",
    avatar: "https://i.pravatar.cc/120?img=15",
    rating: 4.8,
    students: 48230,
  },
  neha: {
    id: "ins_neha",
    name: "Prof. Neha Singh",
    title: "Database Systems",
    avatar: "https://i.pravatar.cc/120?img=45",
    rating: 4.7,
    students: 31980,
  },
  ankit: {
    id: "ins_ankit",
    name: "Prof. Ankit Verma",
    title: "Operating Systems",
    avatar: "https://i.pravatar.cc/120?img=33",
    rating: 4.8,
    students: 27410,
  },
  karan: {
    id: "ins_karan",
    name: "Prof. Karan Shah",
    title: "Computer Networks",
    avatar: "https://i.pravatar.cc/120?img=51",
    rating: 4.6,
    students: 19850,
  },
  pooja: {
    id: "ins_pooja",
    name: "Prof. Pooja Patel",
    title: "Engineering Mathematics",
    avatar: "https://i.pravatar.cc/120?img=47",
    rating: 4.7,
    students: 22300,
  },
};

/* ─────────────────────────────  Courses  ───────────────────────────── */

export const courses: Course[] = [
  {
    id: "crs_dsa",
    slug: "data-structures-using-cpp",
    program: "dsa",
    title: "Data Structures Using C++",
    category: "Computer Science",
    level: "Beginner",
    instructor: instructors.rohit,
    price: 1499,
    originalPrice: 2499,
    rating: 4.6,
    ratingCount: 320,
    durationHours: 12,
    lectures: 42,
    language: "English",
    thumbnail:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=60",
    badge: "Bestseller",
    popular: true,
    tags: ["C++", "DSA", "Problem Solving"],
    plannerUrl: "/planners/dsa-cpp-planner.pdf",
  },
  {
    id: "crs_dbms",
    slug: "database-management-systems",
    program: "btech-bca",
    title: "Database Management Systems",
    category: "Computer Science",
    level: "Intermediate",
    instructor: instructors.neha,
    price: 999,
    originalPrice: 1999,
    rating: 4.7,
    ratingCount: 410,
    durationHours: 15,
    lectures: 50,
    language: "English",
    thumbnail:
      "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=800&q=60",
    badge: "50% OFF",
    popular: true,
    tags: ["SQL", "Normalization", "Transactions"],
    plannerUrl: "/planners/dbms-planner.pdf",
  },
  {
    id: "crs_os",
    slug: "operating-systems",
    program: "gate",
    title: "Operating Systems",
    category: "Computer Science",
    level: "Intermediate",
    instructor: instructors.ankit,
    price: 1299,
    originalPrice: 2199,
    rating: 4.8,
    ratingCount: 512,
    durationHours: 14,
    lectures: 46,
    language: "English",
    thumbnail:
      "https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=800&q=60",
    popular: true,
    tags: ["Processes", "Scheduling", "Memory"],
    plannerUrl: "/planners/os-planner.pdf",
  },
  {
    id: "crs_cn",
    slug: "computer-networks",
    program: "gate",
    title: "Computer Networks",
    category: "Computer Science",
    level: "Beginner",
    instructor: instructors.karan,
    price: 1199,
    originalPrice: 1999,
    rating: 4.6,
    ratingCount: 298,
    durationHours: 8,
    lectures: 36,
    language: "English",
    thumbnail:
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=60",
    tags: ["TCP/IP", "OSI", "Routing"],
    plannerUrl: "/planners/networks-planner.pdf",
  },
  {
    id: "crs_math",
    slug: "engineering-mathematics-ii",
    program: "btech-bca",
    title: "Engineering Mathematics II",
    category: "Computer Science",
    level: "Beginner",
    instructor: instructors.pooja,
    price: 799,
    originalPrice: 1499,
    rating: 4.5,
    ratingCount: 256,
    durationHours: 10,
    lectures: 38,
    language: "Hindi",
    thumbnail:
      "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=800&q=60",
    tags: ["Calculus", "Linear Algebra"],
    plannerUrl: "/planners/maths-planner.pdf",
  },
  {
    id: "crs_oop",
    slug: "object-oriented-programming-java",
    program: "btech-bca",
    title: "Object Oriented Programming in Java",
    category: "Information Technology",
    level: "Intermediate",
    instructor: instructors.rohit,
    price: 1299,
    originalPrice: 2299,
    rating: 4.6,
    ratingCount: 344,
    durationHours: 13,
    lectures: 44,
    language: "English",
    thumbnail:
      "https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=800&q=60",
    badge: "New",
    popular: true,
    tags: ["Java", "OOP", "Design"],
    plannerUrl: "/planners/java-planner.pdf",
  },
  {
    id: "crs_de",
    slug: "digital-electronics",
    program: "gate",
    title: "Digital Electronics",
    category: "Electronics",
    level: "Beginner",
    instructor: instructors.ankit,
    price: 999,
    originalPrice: 1999,
    rating: 4.7,
    ratingCount: 401,
    durationHours: 11,
    lectures: 40,
    language: "English",
    thumbnail:
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=800&q=60",
    badge: "50% OFF",
    tags: ["Logic Gates", "Flip-Flops"],
    plannerUrl: "/planners/digital-electronics-planner.pdf",
  },
  {
    id: "crs_se",
    slug: "software-engineering",
    program: "btech-bca",
    title: "Software Engineering",
    category: "Information Technology",
    level: "Intermediate",
    instructor: instructors.pooja,
    price: 1199,
    originalPrice: 1999,
    rating: 4.8,
    ratingCount: 298,
    durationHours: 12,
    lectures: 41,
    language: "English",
    tags: ["SDLC", "Agile", "Testing"],
    popular: true,
    thumbnail:
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=60",
    plannerUrl: "/planners/software-engineering-planner.pdf",
  },
  {
    id: "crs_coa",
    slug: "computer-organization-architecture",
    program: "gate",
    title: "Computer Organization & Architecture",
    category: "Computer Science",
    level: "Intermediate",
    instructor: instructors.ankit,
    price: 1399,
    originalPrice: 2299,
    rating: 4.7,
    ratingCount: 180,
    durationHours: 16,
    lectures: 52,
    language: "English",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=60",
    popular: true,
    tags: ["CPU", "Memory Hierarchy", "I/O"],
    plannerUrl: "/planners/coa-planner.pdf",
  },
  {
    id: "crs_toc",
    slug: "theory-of-computation",
    program: "gate",
    title: "Theory of Computation",
    category: "Computer Science",
    level: "Advanced",
    instructor: instructors.pooja,
    price: 1099,
    originalPrice: 1899,
    rating: 4.9,
    ratingCount: 120,
    durationHours: 18,
    lectures: 48,
    language: "English",
    thumbnail: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    popular: true,
    tags: ["Automata", "Context Free Grammar", "Turing Machines"],
    plannerUrl: "/planners/toc-planner.pdf",
  },
  {
    id: "crs_cd",
    slug: "compiler-design",
    program: "gate",
    title: "Compiler Design",
    category: "Computer Science",
    level: "Advanced",
    instructor: instructors.ankit,
    price: 1199,
    originalPrice: 1999,
    rating: 4.6,
    ratingCount: 95,
    durationHours: 14,
    lectures: 44,
    language: "English",
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=60",
    tags: ["Lexical Analysis", "Parsing", "Code Generation"],
    plannerUrl: "/planners/compiler-planner.pdf",
  },
  {
    id: "crs_discrete",
    slug: "discrete-mathematics",
    program: "btech-bca",
    title: "Discrete Mathematics",
    category: "Computer Science",
    level: "Intermediate",
    instructor: instructors.pooja,
    price: 899,
    originalPrice: 1599,
    rating: 4.7,
    ratingCount: 155,
    durationHours: 12,
    lectures: 40,
    language: "Hindi",
    thumbnail: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=60",
    tags: ["Set Theory", "Graph Theory", "Logic"],
    plannerUrl: "/planners/discrete-maths-planner.pdf",
  },
  {
    id: "crs_micro",
    slug: "microprocessors-microcontrollers",
    program: "btech-bca",
    title: "Microprocessors & Microcontrollers",
    category: "Electronics",
    level: "Intermediate",
    instructor: instructors.ankit,
    price: 1299,
    originalPrice: 2199,
    rating: 4.6,
    ratingCount: 110,
    durationHours: 15,
    lectures: 45,
    language: "English",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=60",
    tags: ["8085", "8086", "Embedded Systems"],
    plannerUrl: "/planners/micro-planner.pdf",
  },
  {
    id: "crs_ai",
    slug: "artificial-intelligence",
    program: "btech-bca",
    title: "Artificial Intelligence",
    category: "Computer Science",
    level: "Intermediate",
    instructor: instructors.rohit,
    price: 1599,
    originalPrice: 2699,
    rating: 4.8,
    ratingCount: 210,
    durationHours: 16,
    lectures: 48,
    language: "English",
    thumbnail: "https://images.unsplash.com/photo-1555255707-c079664889ec?auto=format&fit=crop&w=800&q=60",
    tags: ["Search Algorithms", "Neural Networks", "NLP"],
    plannerUrl: "/planners/ai-planner.pdf",
  },
];

export const courseBySlug = (slug: string) =>
  courses.find((c) => c.slug === slug);

/* ─────────────────────────  Enrolled / progress  ───────────────────────── */

export const enrolledCourses: EnrolledCourse[] = [
  { course: courses[0], progress: 65, lastAccessed: "2026-06-02T18:00:00Z" },
  { course: courses[1], progress: 45, lastAccessed: "2026-06-01T10:30:00Z" },
  { course: courses[2], progress: 78, lastAccessed: "2026-05-31T20:15:00Z" },
  { course: courses[4], progress: 30, lastAccessed: "2026-05-29T08:00:00Z" },
];

export const recommendedCourses: Course[] = courses.filter((c) => c.popular);

/* ─────────────────────────────  Live classes  ───────────────────────────── */

export const liveClasses: LiveClass[] = [
  {
    id: "lc_dsa",
    title: "Data Structures & Algorithms",
    topic: "Arrays and Linked Lists",
    instructor: instructors.rohit,
    startsAt: "2026-06-03T15:30:00Z",
    endsAt: "2026-06-03T17:00:00Z",
    status: "Upcoming",
  },
  {
    id: "lc_os",
    title: "Operating Systems",
    topic: "Process Scheduling",
    instructor: instructors.ankit,
    startsAt: "2026-06-03T13:30:00Z",
    endsAt: "2026-06-03T15:00:00Z",
    status: "Live",
  },
  {
    id: "lc_dbms",
    title: "Database Management Systems",
    topic: "Normalization in DBMS",
    instructor: instructors.neha,
    startsAt: "2026-06-04T12:30:00Z",
    endsAt: "2026-06-04T14:00:00Z",
    status: "Upcoming",
  },
  {
    id: "lc_cn",
    title: "Computer Networks",
    topic: "TCP/IP Model",
    instructor: instructors.karan,
    startsAt: "2026-06-05T14:00:00Z",
    endsAt: "2026-06-05T15:30:00Z",
    status: "Upcoming",
  },
  {
    id: "lc_math",
    title: "Engineering Mathematics",
    topic: "Linear Algebra & Matrices",
    instructor: instructors.pooja,
    startsAt: "2026-06-06T10:00:00Z",
    endsAt: "2026-06-06T11:30:00Z",
    status: "Upcoming",
  },
  {
    id: "lc_se",
    title: "Software Engineering",
    topic: "Agile Methodologies",
    instructor: instructors.pooja,
    startsAt: "2026-06-06T16:00:00Z",
    endsAt: "2026-06-06T17:30:00Z",
    status: "Upcoming",
  },
  {
    id: "lc_coa",
    title: "Computer Organization",
    topic: "Pipelining & Hazards",
    instructor: instructors.ankit,
    startsAt: "2026-06-07T11:00:00Z",
    endsAt: "2026-06-07T12:30:00Z",
    status: "Upcoming",
  },
];

/* ─────────────────────────────  Announcements  ──────────────────────────── */

export const announcements: Announcement[] = [
  {
    id: "an_1",
    title: "New Semester Courses Launched",
    body: "We just launched 12 new semester courses. Explore them now.",
    date: "2026-05-06",
    tone: "info",
  },
  {
    id: "an_2",
    title: "Exam-Time Offer — 40% OFF",
    body: "Get up to 40% off on all courses for a limited time.",
    date: "2026-05-05",
    tone: "offer",
  },
  {
    id: "an_3",
    title: "Live Class Schedule Updated",
    body: "Check out the updated live-class timetable for this week.",
    date: "2026-05-05",
    tone: "schedule",
  },
];

/* ─────────────────────────────────  Orders  ─────────────────────────────── */

export const orders: Order[] = [
  { id: "ORD1234", date: "2026-05-06", course: "Data Structures Using C++", amount: 1499, status: "Success" },
  { id: "ORD1233", date: "2026-05-05", course: "DBMS Complete Course", amount: 999, status: "Success" },
  { id: "ORD1232", date: "2026-04-29", course: "Operating Systems", amount: 1299, status: "Success" },
  { id: "ORD1231", date: "2026-04-25", course: "Computer Networks", amount: 1199, status: "Failed" },
  { id: "ORD1230", date: "2026-04-20", course: "Engineering Mathematics II", amount: 799, status: "Success" },
];

/* ─────────────────────────────  Learning stats  ─────────────────────────── */

export const learningStats: LearningStats = {
  enrolledCourses: 12,
  averageProgress: 68,
  certificatesEarned: 8,
  hoursLearned: 245,
  lessonsCompleted: 128,
  lessonsTotal: 186,
  quizzesAttempted: 32,
  quizzesTotal: 45,
  averageScore: 78,
  overallProgress: 68,
};

/* ─────────────────────────────  Exam categories  ────────────────────────── */

export const examCategories: ExamCategory[] = [
  {
    id: "gate",
    name: "GATE",
    icon: "🎯",
    tracks: ["CSE", "ECE", "Mechanical", "Civil"],
    accent: "from-rose-100 to-rose-50",
  },
  {
    id: "core",
    name: "Core Engineering",
    icon: "⚙️",
    tracks: ["Sem 1–8", "Backlog Booster"],
    accent: "from-amber-100 to-amber-50",
  },
  {
    id: "placement",
    name: "Placement Prep",
    icon: "💼",
    tracks: ["DSA", "Aptitude", "Interview"],
    accent: "from-violet-100 to-violet-50",
  },
  {
    id: "psu",
    name: "PSU Exams",
    icon: "🏛️",
    tracks: ["ISRO", "BARC", "DRDO"],
    accent: "from-sky-100 to-sky-50",
  },
  {
    id: "programming",
    name: "Programming",
    icon: "💻",
    tracks: ["C++", "Java", "Python", "Web"],
    accent: "from-emerald-100 to-emerald-50",
  },
  {
    id: "skills",
    name: "EE Skills",
    icon: "🚀",
    tracks: ["AI/ML", "Cloud", "DevOps"],
    accent: "from-indigo-100 to-indigo-50",
  },
];
