/**
 * Seed script — refactored to use autogenerated UUIDs and relational connections.
 */
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { courses, instructors, liveClasses, orders, announcements } from "../src/lib/mock-data";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding EngineeringExpert with UUIDs…");

  // Clear existing data to avoid conflicts with new ID structure
  // Using a specific order to avoid foreign key violations
  await prisma.otp.deleteMany();
  await prisma.wishlist.deleteMany();
  await prisma.lessonProgress.deleteMany();
  await prisma.enrollment.deleteMany();
  await prisma.liveClass.deleteMany();
  await prisma.lesson.deleteMany();
  await prisma.order.deleteMany();
  await prisma.announcement.deleteMany();
  await prisma.course.deleteMany();
  await prisma.instructor.deleteMany();
  await prisma.user.deleteMany();

  const hashedPassword = await bcrypt.hash("password123", 10);

  // 1. Instructors
  const instructorMap = new Map<string, string>(); // mockId -> dbId
  for (const ins of Object.values(instructors)) {
    const created = await prisma.instructor.create({
      data: {
        name: ins.name,
        title: ins.title,
        avatar: ins.avatar,
        rating: ins.rating,
        students: ins.students,
      },
    });
    instructorMap.set(ins.id, created.id);
  }

  // 2. Courses
  const courseMap = new Map<string, string>(); // mockSlug -> dbId
  for (const c of courses) {
    const dbInstructorId = instructorMap.get(c.instructor.id);
    if (!dbInstructorId) continue;

    const created = await prisma.course.create({
      data: {
        slug: c.slug,
        title: c.title,
        category: c.category,
        level: c.level,
        price: c.price,
        originalPrice: c.originalPrice,
        rating: c.rating,
        ratingCount: c.ratingCount,
        durationHours: c.durationHours,
        lectures: c.lectures,
        language: c.language,
        thumbnail: c.thumbnail,
        badge: c.badge,
        tags: c.tags,
        plannerUrl: c.plannerUrl,
        instructorId: dbInstructorId,
        popular: c.popular ?? false,
      },
    });
    courseMap.set(c.slug, created.id);
  }

  // 3. Demo student
  const user = await prisma.user.create({
    data: {
      name: "Aditya Kumar",
      email: "aditya.kumar@email.com",
      password: hashedPassword,
      emailVerified: new Date(),
      avatar: "https://i.pravatar.cc/160?img=12",
      role: "student",
    },
  });

  // 4. Enrollments for demo student
  console.log("📚 Adding enrollments for demo student…");
  const enrolledSlugs = ["data-structures-using-cpp", "database-management-systems", "operating-systems"];
  for (const slug of enrolledSlugs) {
    const dbCourseId = courseMap.get(slug);
    if (dbCourseId) {
      await prisma.enrollment.create({
        data: {
          userId: user.id,
          courseId: dbCourseId,
          progress: Math.floor(Math.random() * 100),
        },
      });
    }
  }

  // 5. Live classes
  const lcCourseMap: Record<string, string> = {
    lc_dsa:  "data-structures-using-cpp",
    lc_os:   "operating-systems",
    lc_dbms: "database-management-systems",
  };

  for (const lc of liveClasses) {
    const courseSlug = lcCourseMap[lc.id];
    const dbCourseId = courseSlug ? courseMap.get(courseSlug) : null;
    const dbInstructorId = instructorMap.get(lc.instructor.id);
    
    if (!dbInstructorId) continue;

    await prisma.liveClass.create({
      data: {
        title: lc.title,
        topic: lc.topic,
        startsAt: new Date(lc.startsAt),
        endsAt: new Date(lc.endsAt),
        status: lc.status === "Ongoing" ? "Ongoing" : lc.status,
        instructorId: dbInstructorId,
        courseId: dbCourseId ?? null,
      },
    });
  }

  // 6. Orders
  for (const o of orders) {
    await prisma.order.create({
      data: {
        amount: o.amount,
        status: o.status,
        course: o.course,
        createdAt: new Date(o.date),
        userId: user.id,
      },
    });
  }

  // 7. Announcements
  for (const a of announcements) {
    await prisma.announcement.create({
      data: {
        title: a.title,
        body: a.body,
        tone: a.tone,
        date: new Date(a.date)
      },
    });
  }

  console.log("✅ Seed complete with autogenerated UUIDs.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
